#!/usr/bin/env node
'use strict';
/*
  render.js: USER.md + rules/*.md  ->  per-AI instruction files.

  usage:
    node render/render.js [--dir <project>] [--targets claude,agents,gemini,chatgpt,prompt] [--check] [--contract]

  --dir       project folder holding USER.md and rules/ (default: cwd)
  --targets   which renders to write; default: from <dir>/.agent-personalizer.json, else "claude,agents"
  --check     render to memory and compare with what is on disk; exit 1 on any drift, 0 when clean
  --contract  print the inject:true rules (universal + personal) to stdout and exit; for session-start hooks

  Rendered text lives between two markers inside the target file. Text outside the
  markers is yours and is preserved. Never edit inside the markers; edit USER.md or
  rules/ and re-render.

  No network. No environment variables read. No secrets written.
*/
const fs = require('fs');
const path = require('path');

const BEGIN = '<!-- agent-personalizer:begin -->';
const END = '<!-- agent-personalizer:end -->';
const TARGETS = JSON.parse(fs.readFileSync(path.join(__dirname, 'targets.json'), 'utf8'));

function arg(name, dflt) {
  const i = process.argv.indexOf(name);
  if (i === -1) return dflt;
  const v = process.argv[i + 1];
  return v && !v.startsWith('--') ? v : true;
}

function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) return { meta: {}, body: text };
  const meta = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!kv) continue;
    let v = kv[2].trim();
    if (v.startsWith('[') && v.endsWith(']')) v = v.slice(1, -1).split(',').map(s => s.trim()).filter(Boolean);
    else if (v === 'true') v = true;
    else if (v === 'false') v = false;
    meta[kv[1]] = v;
  }
  return { meta, body: text.slice(m[0].length) };
}

function parseSections(body) {
  // "## name" headings split the rule into blocks; text before the first heading is ignored.
  const sections = {};
  let current = null;
  for (const line of body.split('\n')) {
    const h = line.match(/^##\s+(.+?)\s*$/);
    if (h) { current = h[1].trim(); sections[current] = []; continue; }
    if (current) sections[current].push(line);
  }
  for (const k of Object.keys(sections)) sections[k] = sections[k].join('\n').trim();
  return sections;
}

function loadRules(dir) {
  const rdir = path.join(dir, 'rules');
  if (!fs.existsSync(rdir)) return [];
  return fs.readdirSync(rdir)
    .filter(f => /^\d{2}-.*\.md$/.test(f))
    .sort()
    .map(f => {
      const text = fs.readFileSync(path.join(rdir, f), 'utf8');
      const { meta, body } = parseFrontmatter(text);
      const sections = parseSections(body);
      if (!sections.universal) throw new Error(`rules/${f}: missing "## universal" block`);
      return { file: f, meta, sections };
    });
}

function loadProfile(dir) {
  const p = path.join(dir, 'USER.md');
  if (!fs.existsSync(p)) return null;
  const text = fs.readFileSync(p, 'utf8');
  // drop the leading H1 and the trailing italic template note
  return text.replace(/^#\s+USER\.md\s*\n/, '').replace(/\n---\n\*Template from agent-personalizer[^\n]*\n?$/, '').trim();
}

function renderRule(rule, target, key) {
  const s = rule.sections;
  const out = [`### ${rule.meta.title || rule.meta.id || rule.file}`, '', s.universal];
  if (target.personal && s.personal) out.push('', s.personal);
  if (target.binding && s[`binding:${target.binding}`]) out.push('', s[`binding:${target.binding}`]);
  if (target.origin && s.origin) out.push('', s.origin.split('\n').map(l => `> ${l}`).join('\n'));
  return out.join('\n');
}

function rulesFor(rules, key) {
  return rules.filter(r => !Array.isArray(r.meta.surfaces) || r.meta.surfaces.includes(key));
}

function renderTarget(key, target, profile, rules) {
  const lines = [`## ${target.header}`, '', '_Generated by agent-personalizer from `USER.md` and `rules/`. Edit those, then re-render. Do not edit between the markers._', ''];
  if (target.boxes) {
    const box1 = profile || '(no USER.md found)';
    const box2 = rulesFor(rules, key).map(r => r.sections.universal).join('\n\n');
    const warn = (label, text) => text.length > target.limit ? `\n> ${label} is ${text.length} characters; the box allows about ${target.limit}. Trim before pasting.` : `\n> ${label}: ${text.length} characters.`;
    lines.push('### Box 1: "What would you like ChatGPT to know about you?"', '', '```', box1, '```', warn('Box 1', box1), '');
    lines.push('### Box 2: "How would you like ChatGPT to respond?"', '', '```', box2, '```', warn('Box 2', box2));
    return lines.join('\n');
  }
  if (target.profile && profile) lines.push('## Profile', '', profile, '');
  lines.push('## Rules', '');
  for (const r of rulesFor(rules, key)) lines.push(renderRule(r, target, key), '');
  return lines.join('\n').trimEnd();
}

function splice(existing, block) {
  const body = `${BEGIN}\n${block}\n${END}`;
  if (existing == null) return `${body}\n`;
  const a = existing.indexOf(BEGIN);
  const b = existing.indexOf(END);
  if (a === -1 || b === -1 || b < a) return `${existing.trimEnd()}\n\n${body}\n`;
  return existing.slice(0, a) + body + existing.slice(b + END.length);
}

function between(text) {
  const a = text.indexOf(BEGIN);
  const b = text.indexOf(END);
  if (a === -1 || b === -1 || b < a) return null;
  return text.slice(a + BEGIN.length, b).replace(/^\n/, '').replace(/\n$/, '');
}

function main() {
  const dir = path.resolve(String(arg('--dir', process.cwd())));
  const check = process.argv.includes('--check');
  const contract = process.argv.includes('--contract');
  const rules = loadRules(dir);
  const profile = loadProfile(dir);

  if (contract) {
    const inject = rules.filter(r => r.meta.inject === true);
    const out = ['[agent-personalizer] Session-start contract. These rules win at the moment of decision; they are injected in full, every session.', ''];
    for (const r of inject) {
      out.push(`## ${r.meta.title || r.meta.id}`, '', r.sections.universal);
      if (r.sections.personal) out.push('', r.sections.personal);
      out.push('');
    }
    process.stdout.write(out.join('\n'));
    return;
  }

  let targets;
  const cfgPath = path.join(dir, '.agent-personalizer.json');
  const explicit = arg('--targets', null);
  if (explicit && explicit !== true) targets = String(explicit).split(',').map(s => s.trim());
  else if (fs.existsSync(cfgPath)) targets = JSON.parse(fs.readFileSync(cfgPath, 'utf8')).targets || ['claude', 'agents'];
  else targets = ['claude', 'agents'];

  let drift = 0;
  for (const key of targets) {
    const target = TARGETS[key];
    if (!target) { console.error(`unknown target "${key}" (known: ${Object.keys(TARGETS).join(', ')})`); process.exit(2); }
    const block = renderTarget(key, target, profile, rules);
    const file = path.join(dir, target.file);
    const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (check) {
      const current = existing == null ? null : between(existing);
      if (current === null) { console.log(`DRIFT  ${target.file}: missing or no marker block`); drift++; }
      else if (current !== block) { console.log(`DRIFT  ${target.file}: rendered block differs from source`); drift++; }
      else console.log(`ok     ${target.file}`);
      continue;
    }
    fs.writeFileSync(file, splice(existing, block));
    console.log(`wrote  ${target.file}`);
  }
  if (check) {
    console.log(drift ? `\n${drift} file(s) drifted. Re-render with: node render/render.js --dir ${dir}` : '\nclean: every rendered file matches its source');
    process.exit(drift ? 1 : 0);
  }
}

main();
